import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: "#fafafa",
	},
	container: {
		flex: 1,
		paddingHorizontal: 20,
		paddingTop: 16,
	},
	logo: {
		width: 25,
		height: 25,
		marginTop: 2,
	},
	iconRow: {
		flexDirection: "row",
		gap: 7,
	},
	greeting: {
		fontSize: 22,
		fontWeight: "800",
		color: "#191919",
		marginBottom: 12,
	},
	profileRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 12,
	},
	walletBadge: {
		backgroundColor: "#e5e5e5",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 100,
		marginBottom: 16,
		flexDirection: "row",
		alignItems: "center",
	},
	walletText: {
		fontSize: 13,
		color: "#191919",
		fontWeight: "600",
		letterSpacing: 0.4,
	},
	createJob: {
		backgroundColor: "#191919",
		color: "#ededed",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 100,
		marginBottom: 16,
		flexDirection: "row",
		alignItems: "center",
		fontSize: 13,
		fontWeight: "600",
		letterSpacing: 0.4,
	},
	balanceCard: {
		backgroundColor: "#fff",
		padding: 20,
		borderRadius: 16,
		borderWidth: 1,
		borderColor: "#ededed",
		alignItems: "flex-start",
		flex: 1,
	},
	balanceLabel: {
		fontSize: 15,
		color: "#8e8e8e",
		marginBottom: 4,
		fontWeight: "500",
	},
	balanceValue: {
		fontSize: 28,
		fontWeight: "700",
		color: "#191919",
	},
	activeJobCard: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		backgroundColor: "#fff",
		borderRadius: 14,
		borderWidth: 1,
		borderColor: "#ededed",
		padding: 18,
		marginBottom: 20,
		shadowColor: "#000",
		shadowOpacity: 0.03,
		shadowOffset: { width: 0, height: 2 },
		shadowRadius: 8,
		elevation: 2,
	},
	activeJobText: {
		flex: 1,
	},
	activeJobLabel: {
		color: "#8e8e8e",
		fontSize: 14,
		fontWeight: "600",
		marginBottom: 2,
	},
	activeJobTitle: {
		fontSize: 17,
		fontWeight: "700",
		color: "#191919",
	},
	activeJobClient: {
		fontSize: 12,
		fontWeight: "500",
		marginTop: 6,
		alignSelf: "flex-start",
		backgroundColor: "#e5e5e5",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 100,
		flexDirection: "row",
		alignItems: "center",
	},
	resumeButton: {
		backgroundColor: "#191919",
		paddingVertical: 8,
		paddingHorizontal: 18,
		borderRadius: 8,
		marginLeft: 18,
	},
	resumeButtonText: {
		color: "#fff",
		fontWeight: "700",
		fontSize: 15,
	},
	primaryButton: {
		backgroundColor: "#191919",
		paddingVertical: 17,
		borderRadius: 16,
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 28,
		flexDirection: "row",
	},
	primaryButtonText: {
		color: "#fff",
		fontSize: 17,
		fontWeight: "700",
		letterSpacing: 0.1,
	},
	bottomActions: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: 28,
		gap: 12,
	},
	scanButton: {
		backgroundColor: "#191919",
		borderRadius: 16,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		flex: 1,
		paddingVertical: 17,
	},
	scanButtonText: {
		color: "#fff",
		fontSize: 17,
		fontWeight: "700",
		letterSpacing: 0.1,
	},
	createJobButton: {
		width: 54,
		height: 54,
		backgroundColor: "#fff",
		borderRadius: 16,
		borderWidth: 1,
		borderColor: "#ededed",
		alignItems: "center",
		justifyContent: "center",
		marginLeft: 0,
		shadowColor: "#000",
		shadowOpacity: 0.07,
		shadowOffset: { width: 0, height: 2 },
		shadowRadius: 6,
		elevation: 2,
	},
});
